spring.application.name=fintech


## ENDEREÇO DO BANCO DE DADOS.
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL

## USUÁRIO DO BANCO DE DADOS:
spring.datasource.username=RM566918

## SENHA DO BANCO DE DADOS
spring.datasource.password=270994

## MOSTRAR AS INSTRUÇÕES SQL EXECUTADAS NO BANCO DE DADOS.
spring.jpa.show-sql=true 